name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

#    - name: Set up JDK 21
#      uses: actions/setup-java@v3
#      with:
#        distribution: 'adopt'
#        java-version: '21'

    - name: Build with Maven
      run: mvn clean package

    - name: Build and Start Docker Compose Services
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml up -d

    - name: Verification
      run: docker-compose logs -f
  
#  deploy:
