name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml # mvn clean package

    - name: Install Compose
      uses: ndeloof/install-compose-action@v0.0.1
      with:
        version: v2.29.1 # defaults to 'latest'
        legacy: true    # will also install in PATH as `docker-compose`

    - name: Verification docker-compose
      run: docker-compose --version

    - name: Build and Start Docker Compose Services
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml up -d

    - name: Verification
      run: |
        docker-compose ps -a

  
#  deploy:
